In [181]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(1)

In [24]:
# vector p
listp = [0.05, 0.1, 0.15, 0.2, 0.25, 0.25]
p = np.array(listp)

out = np.random.multinomial(50,p)
print(out)

[ 1  5 12  9 10 13]


In [34]:
outp = []
for i in out:
    outp.append(i/50)

print(outp)

[0.02, 0.1, 0.24, 0.18, 0.2, 0.26]


In [50]:
m = len(nSample)
k = len(p)
ProbEst = np.empty([m, k], dtype=float)
nSample = [10,40,50]
i = 0

for n in nSample:
    out = []
    #out.append(np.random.multinomial(n, p)/n)
    ProbEst[i] = np.random.multinomial(n, p)/n
    i+= 1

print(ProbEst)
    
        

[[0.    0.    0.2   0.3   0.2   0.3  ]
 [0.025 0.225 0.15  0.15  0.225 0.225]
 [0.06  0.12  0.12  0.12  0.3   0.28 ]]


In [ ]:
def estimate(p, nSample):
  """
  Estimate the value of p by drawing samples with varying number of cast
  Input:
    - p:    a 1-D numpy array of size k (number of events), 
            encoding the probability of each of the k outcomes
    - nSample: a 1-D numpy array of size m specifying the sample sizes.
            Effectively, we run m number of experiments,
            with each experiment drawing nSample[j] number of samples (j=0,...,m-1)
  Outputs:
    - ProbEst: an m-by-k matrix (2-D numpy array), 
                whose j-th row (j >= 0) encodes the probability estimate 
                for the k events based on nSample[j] number of samples
  """  

  np.random.seed(1)
  k = p.size
  m = nSample.size
  ProbEst = np.empty([m, k], dtype=float)
  # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
  i = 0
  for n in nSample:
    ProbEst[i] = np.random.multinomial(n, p)/n
    i+= 1
  # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
  return ProbEst

"""
Unit test case below
You should get the following results:
[[0.         0.2        0.         0.2        0.4        0.2       ]
 [0.         0.05       0.15       0.2        0.3        0.3       ]
 [0.03333333 0.13333333 0.1        0.3        0.33333333 0.1       ]]
"""
p = np.array([0.05, 0.1, 0.15, 0.2, 0.25, 0.25])
nSample = np.arange(10, 40, 10)
ProbEst = estimate(p, nSample)
print(ProbEst)

In [52]:
1000%10
1000/100.



100.0

In [65]:
np.random.seed(1)

  # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
nSample_start = 10
nSample_end = 1000
k = p.size
nSample = np.arange(nSample_start, nSample_end+1, nSample_end/nSample_start)
m = nSample.size
print(nSample.size)
  #ProbEst = np.empty([m, k], dtype=float)
  # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
  #i = 0
  #for n in nSample:
    #ProbEst[i] = np.random.multinomial(n, p)/n
    #i+= 1
  # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
  #return ProbEst
  
 

  # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
  #return ProbEst

p = np.array([0.05, 0.1, 0.15, 0.2, 0.25, 0.25])
#probEst_eff = estimate_efficient(p, 10, 30)
#print(probEst_eff)

int(nSample_end/nSample_start)

10


100

In [99]:
p = np.array([0.05, 0.1, 0.15, 0.2, 0.25, 0.25])
nSample_start = 10
nSample_end = 1000
k = p.size
m = int(nSample_end/nSample_start)
ProbEst = np.empty([m, k], dtype=float)

outcomes = np.random.multinomial(nSample_start, p, m)

cum_out = cum_outcomes = np.cumsum(outcomes, axis = 0)


i = nSample_start

for n in range(m):
    ProbEst[n] = cum_out[n]/i
    i += nSample_start
    
print(ProbEst)


100
[[0.         0.1        0.2        0.4        0.2        0.1       ]
 [0.         0.15       0.2        0.3        0.25       0.1       ]
 [0.03333333 0.1        0.16666667 0.23333333 0.26666667 0.2       ]
 [0.05       0.1        0.125      0.2        0.325      0.2       ]
 [0.04       0.1        0.1        0.18       0.28       0.3       ]
 [0.03333333 0.1        0.11666667 0.2        0.28333333 0.26666667]
 [0.02857143 0.11428571 0.11428571 0.21428571 0.25714286 0.27142857]
 [0.025      0.1        0.1375     0.225      0.25       0.2625    ]
 [0.02222222 0.1        0.13333333 0.22222222 0.25555556 0.26666667]
 [0.02       0.11       0.12       0.22       0.25       0.28      ]
 [0.01818182 0.11818182 0.11818182 0.24545455 0.22727273 0.27272727]
 [0.01666667 0.11666667 0.13333333 0.23333333 0.225      0.275     ]
 [0.01538462 0.10769231 0.13076923 0.23076923 0.23076923 0.28461538]
 [0.02857143 0.10714286 0.12857143 0.22857143 0.23571429 0.27142857]
 [0.02666667 0.1        0.1333

In [102]:
X = np.array([[1.30,2.21,3.23,4.12], [1.56, 6.23, 6.34, 9.23], [0.11, 0.92, 3.84, 0.18]])

X_mean = X.mean(0)
X_std = X.std(0)
print(X_mean)
print(X_std)
print(X.size)

[0.99 3.12 4.47 4.51]
[0.63124216 2.26128282 1.34553583 3.70492465]
12


In [179]:
#2.2.1
X = np.array([[2.0, 1.0, 3.0], [3.0, 6.0, 2.0]])
y =  np.array([1.0, 1.0])
theta = np.array([1.0, 2.0,1.0])
m = X.size

oT = np.transpose(theta) 

np.dot(X, oT)

print(sum(((np.dot(X, oT)-y)**2))/4)



73.0


# Gradient

$\frac{X(X^{T}\Theta)}{m} - \frac{X^{T}y}{m}$

In [260]:
#gradient


X = np.array([[2.0, 1.0, 3.0], [3.0, 6.0, 2.0]])
y =  np.array([1.0, 1.0])
theta = np.array([1.0, 2.0,1.0])
m = len(X)

transX = np.transpose(X)
xTtheta = np.dot(theta, transX)

p1 = (np.dot( xTtheta, X))/m

p2 = (np.dot(transX, y))/m


((np.dot( np.dot(theta, np.transpose(X)), X))/m) - ((np.dot(np.transpose(X), y))/m)



array([30., 51., 25.])

# Gradient descent
$$
\theta = \theta - \alpha\frac{X(X^{T}\Theta)}{m} - \frac{X^{T}y}{m}
$$


In [286]:
# find theta & Loss_record both 1x3 matrices

X = np.array([[2.0, 1.0, 3.0], [3.0, 6.0, 2.0]])
y =  np.array([1.0, 1.0])
theta = np.array([1.0, 2.0, 1.0])
alpha = 0.01
num_iters = 3
m = len(X)

#Iter #1
theta = theta - (alpha*(((np.dot( np.dot(theta, np.transpose(X)), X))/m) - ((np.dot(np.transpose(X), y))/m)))
Loss_record = error = sum(((np.dot(X, np.transpose(theta))-y)**2))/(m*2)


#Iter #2
theta = theta - (alpha*(((np.dot( np.dot(theta, np.transpose(X)), X))/m) - ((np.dot(np.transpose(X), y))/m)))
Loss_record = error = sum(((np.dot(X, np.transpose(theta))-y)**2))/(m*2)
print(theta, Loss_record)


#def gradientDescent(X, y, theta, alpha, num_iters):
#    for i in range(num_iters):
#        Loss_record  = ((np.dot( np.dot(theta, np.transpose(X)), X))/m) - ((np.dot(np.transpose(X), y))/m)
#        theta = theta - (alpha*(((np.dot( np.dot(theta, np.transpose(X)), X))/m) - ((np.dot(np.transpose(X), y))/m)))
#        
#    return theta, Loss_record  


#gradientDescent(X,y, theta, alpha, num_iters)


[0.4855 1.1231 0.5725] 19.365590642499996


In [303]:
ones = np.array([0,0,0])

#num_row, num_col = ones.shape

ones.shape



(3,)

In [304]:
learning_rates = [1.0, 0.1, 0.01, 0.001]
len(learning_rates)


4

In [312]:
X = np.array([[2.0, 1.0, 3.0], [3.0, 6.0, 2.0], [-1, 0, 2.0]])
y = np.array([1.0, 1.0, -1.0])

XT = np.transpose(X)

XTy = np.dot(XT,y)

theta = np.dot((np.dot(np.linalg.inv(X),XTy)), np.linalg.inv(XT)) 


print(XTy)

[6. 7. 3.]


In [355]:
X = np.array([[2.0, 1.0, 3.0], [3.0, 6.0, 2.0], [-1, 0, 2.0]])
y = np.array([1.0, 1.0, -1.0])
m = len(X)

XT = np.transpose(X)
#print(XT)
#print((np.dot(XT,y))/m)

#p1 = np.dot(XT, y)    


#p2 = np.linalg.inv(np.dot(X,XT))

#print(np.dot(np.dot(XT, y),np.linalg.inv(np.dot(X,XT))))

#np.linalg.inv(p1)

#print(np.dot(X,XT))
#print(np.linalg.inv(np.dot(X,XT)))

#Xinv = np.linalg.inv(X)

#print(np.dot(X,y))

#p1 = np.linalg.inv(np.dot(X,XT))
#p2 = np.dot(p1,XT)
#p3 = np.dot(p2,y)

#print(np.linalg.inv(np.dot(X,y)))

trying again for:

$$
\theta = (X^{T}X)^{-1}X^{T}y
$$

In [363]:
XTX = np.dot(XT,X)

invXTX = np.linalg.inv(XTX)



invXTX_XT = np.dot(invXTX,XT)



sol = np.dot(invXTX_XT,y)

print(sol)

[ 0.76470588 -0.17647059 -0.11764706]


In [367]:
# try altogether

theta = np.dot(np.dot(np.linalg.inv(np.dot(np.transpose(X),X)),np.transpose(X)) ,y)

print(theta)

[ 0.76470588 -0.17647059 -0.11764706]


$$
\nabla_{\theta}L(\theta) = \frac{X^{T}(X\theta)}{m} - \frac{X^{T}y}{m}
$$

In [375]:
gradient = ((np.dot( np.dot(theta, np.transpose(X)), X))/m) - ((np.dot(np.transpose(X), y))/m)

m = len(X)
X = np.array([[2.0, 1.0, 3.0], [3.0, 6.0, 2.0]])
y =  np.array([1.0, 1.0])
theta = np.array([1.0, 2.0,1.0])



gradient = (np.dot(np.transpose(X), np.dot(X,theta)) / m) - ((np.dot(np.transpose(X), y)) / m)
print(gradient)

[30. 51. 25.]
