In [3]:
# set up code for this experiment
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

np.random.seed(1)

# Problem 1
## my_euclidian distance scratch work

In [5]:
X_train = np.array([[1, 2], [0, 3], [-1, 1]])
X_test = np.array([[-1, 0], [2, 1]])
num_test = X_test.shape[0]
num_train = X_train.shape[0]
dists = np.zeros((num_test, num_train))

sum(np.square(X_train[0]))

print(num_test)




2


In [6]:
a = np.zeros(num_test)


for i in range(num_test):
    a[i] = sum(np.square(X_test[i]))

print(a)

[1. 5.]


In [7]:
b = np.zeros(num_train)
for j in range(num_train):
    b[j] = sum(np.square(X_train[j]))

print(b)


[5. 9. 2.]


In [8]:
#for i = 0 ... num_test - 1
  #    for j = 0 ... num_train - 1
  #        dists[i, j] = a[i] + b[j] - 2 * np.dot(i-th test example, j-th training example)

# calculate square of the norm of the i-th test example
for i in range(num_test):
  a = sum(np.square(X_test[i]))
  # calculate square of the norm of the i-th train example
  for j in range(num_train):
    b = sum(np.square(X_train[j]))
    # calculate distance for i-th test example & i-th train example
    dists[i,j] = a + b - 2* np.dot(X_test[i], X_train[j])

print(dists)

[[ 8. 10.  1.]
 [ 2.  8.  9.]]


## Step 2:


In [37]:
# TODO:
# find the top k nearest neighbors for each test sample.
# retrieve the corresponding labels of those neighbors.
# Here is the pseudo-code:
# for i = 0 ... num_test-1
#     idx = numpy.argsort(i-th row of dists)
#     neighbors[i] = Y_train(idx[0]), ..., Y_train(idx[k-1])
# return neighbors
# Advanced: You can accelerate the code by, e.g., argsort on the `dists` matrix directly

idx = np.argsort(dists, axis=1)
k = 2
neighbors = np.zeros((num_test, k))
Y_train = np.array([0, 1, 1])

num_test = dists.shape[0]
print(num_test)

for i in range(num_test):
  for k in range(k):
    neighbors[i][k] = Y_train[idx[i][k]]




2


In [47]:
# test answer code


    num_test = dists.shape[0]
    neighbors = np.zeros((num_test, k))

    # sort indices of dists by shortest to longest distance
    idx = np.argsort(dists, axis=1)
  
    # return label for k closest neighbors
    for i in range(num_test):
        for j in range(k):
            neighbors[i][j] = Y_train[idx[i][j]]

k = 3   # you can vary it as 1 or 3
Y_train = np.array([0, 1, 1])
find_k_neighbors(dists, Y_train, k)

print(neighbors)


[[1. 0.]
 [0. 1.]]


Step 3: return label for test set


In [75]:
def euclidean_dist(X_test, X_train):
    dists = np.add(np.sum(X_test ** 2, axis=1, keepdims=True), np.sum(X_train ** 2, axis=1, keepdims=True).T) - 2* X_test @ X_train.T
    return dists

def find_k_neighbors(dists, Y_train, k):
  num_test = dists.shape[0]
  neighbors = np.zeros((num_test, k))
  # sort indices of dists by shortest to longest distance
  idx = np.argsort(dists, axis=1)
  
  # return label for k closest neighbors
  for i in range(num_test):
    for j in range(k):
      neighbors[i][j] = Y_train[idx[i][j]]
  # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
  return neighbors

# Unit test code here (you can uncomment the four lines below to test)
X_train = np.array([[1, 2], [0, 3], [-1, 1]])
X_test = np.array([[-1, 0], [2, 1]])

  
"""
  Inputs:
  - X_test: A numpy array of shape (num_test, dim_feat) containing test data.
  - X_train: A numpy array of shape (num_train, dim_feat) containing training data.
  - Y_train: A numpy array of shape (num_train) containing ground truth labels for training data
  - k: An integer, k nearest neighbors

  Output:
  - Y_pred: A numpy array of shape (num_test). Predicted labels for the test data.

  # TODO:
  # find the labels of k nearest neighbors for each test example,
  # and then find the majority label out of the k labels
  #
  # Here is the pseudo-code:
"""
neighbors = find_k_neighbors(dists, Y_train, k)
dists = euclidean_dist(X_test, X_train)
# initialize empty array for Y_pred of length num_test
Y_pred = np.zeros(num_test, dtype=int)
# calculate most frequent label in neigbors add to Y_pred
for i in range(num_test):
  labels, counts = np.unique(neighbors[i], return_counts=True)
  Y_pred[i] = labels[np.argmax(counts)]
  print(labels, counts)

#print(Y_pred)
print(neighbors)
#print(labels, counts)


  # Y_pred = np.zeros(num_test, dtype=int)  # force dtype=int in case the dataset
  #                                         # stores labels as float-point numbers
  # for i = 0 ... num_test-1
  #     Y_pred[i] = # the most common/frequent label in neighbors[i], you can
  #                 # implement it by using np.unique
  # return Y_pred

[0. 1.] [1 2]
[0. 1.] [1 2]
[[1. 0. 1.]
 [0. 1. 1.]]


In [66]:
ypred = 1
ytrue = 0
int(ypred != ytrue)



1

In [69]:


labels, counts = np.unique(neighbors, return_counts=True)

print(neighbors)
print(labels, counts)

[[1. 0. 1.]
 [0. 1. 1.]]
[0. 1.] [2 4]
